### ISSUE TITLE
Caught comments should be posted in chronological order

### ISSUE THREAD

**Issue by retailcoder** [Zomis/GithubHookSEChatService#68]
Currently the newest comment is being posted first:

> If this is working code, it should be migrated to Code Review (as Brobin suggested). If not, what's the problem? — Fred Larson 45 secs ago
> You might get more feedback on the Code Review Stack Exchange. codereview.stackexchange.com — Brobin 1 min ago

This breaks the space-time continuum of our lovely chatroom!

**Comment by Zomis** [comment]
Not sure if it's a bug or enhancement. Better label it as both.

**Comment by retailcoder** [comment]
What? You don't have a [feature-request] label? ;)
