### ISSUE TITLE
Make ScheduledTasks dynamically configurable

### ISSUE THREAD

**Issue by Zomis** [Zomis/GithubHookSEChatService#70]
This has been a long-planned enhancement but apparently there was no issue from it.

It would be nice to make a simple edit to the database and make it add/modify/remove some scheduled tasks. Scheduled tasks should probably be stored in the database as a `String`, as logic can't really be stored in the database (unless we would want to add Nashorn script support which I don't feel is necessary). The String could be something such as `message(8595, "***RELOAD***")` or `dailyStats(16134)`, etc.. more support for various tasks can be added later.

Additionally, it should also have a `String cronConfiguration` as a `String`, of course, to modify the time and frequency.

**Comment by Vogel612** [comment]
As an alternative to Nashorn scripts you might want to consider Groovy Script evaluation (at runtime). I imagine pseudocode like:

    for (ScheduledTask task : database.getScheduledTasks()) {
          if (task.isDue()) {
                groovyEngine.run(task.getJob());
          }
    }

**Comment by Zomis** [comment]
This is now more configurable. Not using Nashorn or Groovy though, but I'm happy with it!
